stages:
  - test

test:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew test
    - cat build/reports/jacoco/test/html/index.html
  artifacts:
    reports:
      junit: build/test-results/test/**.xml